version: '3'

services:
  posgre:
    image: 'postgres'
    container_name: 'postgresdb'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - data:/var/lib/postgresql/

volumes:
  data: