[tool.poetry]
name = "tfg-dietplanner"
version = "0.1.0"
description = ""
authors = ["Alejandro Olivares <a.olivaresdelrey.pierres@gmail.com>"]
readme = "README.md"
packages = [{include = "tfg_dietplanner"}]

[tool.poetry.dependencies]
python = "^3.10"
invoke = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
