version: 2.1
jobs:
  check-spelling:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install python3 python3-pip -y

      - run:
          name: Install dependencies
          command: | 
            pip install poetry
            poetry config virtualenvs.create false
            poetry install --no-root

      - run:
          name: Run spelling check
          command: invoke workflowSpell
  test:
    docker:
      - image: cimg/base:2023.09
    environment:
      DB_NAME: db.sqlite3
      STATIC_URL: 'static/'
      DATA_RECIPES: './data/recipes.json'
      DATA_INGREDIENTS: "./data/ingredients.csv"
      DEBUG: True
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install python3.10 python3-pip -y
      - run:
          name: Install dependencies
          command: | 
            pip install poetry invoke
            poetry install --no-root

      - run:
          name: Run Tests
          command: invoke test

workflows:
  check-spelling:
    jobs:
      - check-spelling
  test:
    jobs:
      - test