version: 2.1
jobs:
  check-spelling:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install python3 python3-pip -y

      - run:
          name: Install dependencies
          command: pip install invoke

      - run:
          name: Run spelling check
          command: invoke workflowSpell
  test:
    docker:
      - image: cimg/base:2023.09
    environment:
      DB_NAME: dietplanner.sqlite3
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install python3 python3-pip -y
      - run:
          name: Install dependencies
          command: pip install invoke pytest python-decouple django pytest-django
      - run:
          name: Run Tests
          command: invoke test

workflows:
  check-spelling:
    jobs:
      - check-spelling
  test:
    jobs:
      - test