version: 2.1
jobs:
  check-spelling:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install python3 python3-pip -y

      - run:
          name: Install dependencies
          command: pip install invoke

      - run:
          name: Run spelling check
          command: invoke workflowSpell

workflows:
  version: 2
  check-spelling:
    jobs:
      - check-spelling