version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install python3 python3-pip -y
      - run:
          name: Install dependencies
          command: pip install pytest
      - run:
          name: Run Tests
          command: invoke test

workflows:
  version: 2
  test:
    jobs:
      - test